### ISSUE TITLE
When you add an object relationship, the system replacement will set the index for you on the current partition!

### ISSUE THREAD

**Issue by vzhougm** [Haulmont/jmix-core#103]
When you add an object relationship, the system replacement will set the index for you on the current partition!

The index name starts with fk_

![image](https://user-images.githubusercontent.com/49505436/109279706-0a94a880-7855-11eb-8ca5-2cff73cf096d.png)

**Comment by vzhougm** [comment]
but the corresponding index is not added in entity.

**Comment by knstvk** [comment]
What do you mean by current partition?
And what's wrong with that?

**Comment by alexbudarov** [comment]
Will reopen if receive additional information.
