### ISSUE TITLE
Implement the functionality of EntityLoadInfo from CUBA

### ISSUE THREAD

**Issue by gorbunkov** [Haulmont/jmix-core#113]
In CUBA, there is the `EntityLoadInfo` class that stores information about the entity class and its id. The EntityLoadInfo can be serialized into string. We should have something similar in Jmix. There is a `io.jmix.core.Id` class but it doesn't support serialization/deserialization into string.

**Comment by knstvk** [comment]
Use `io.jmix.core.IdSerialization` bean.
