### ISSUE TITLE
Entity with attribute named `id` but without `@Id` annotation

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-core#127]
QA: test this case in UI - it should work. REST doesn't support it.

**Comment by owlet1997** [comment]
**Enviroment:**
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2706-202
IntelliJ version: IntelliJ IDEA 2020.3.1 (Community Edition)

Minimal reproducible example: 
1. create entity newEntity -> add any fields 
2. open tab 'Text' -> remove `@Id` annotation
3. run app

**AR:**
there is an liquibase error
![image](https://user-images.githubusercontent.com/45730069/113402442-0d377000-93b6-11eb-91e0-be38d088a987.png)

**Comment by owlet1997** [comment]
Enviroment:
Jmix version: 0.9.0
Jmix Studio plugin version: 1.0.SNAPSHOT2706-202
IntelliJ version: IntelliJ IDEA 2020.3.1 (Community Edition)

it works:
![image](https://user-images.githubusercontent.com/45730069/113405064-3fe36780-93ba-11eb-8ccc-e42ac9c3fa4e.png)
