### ISSUE TITLE
Incorrect behavior when editing an entity with a composite (embedded) id

### ISSUE THREAD

**Issue by lovtsovaik** [Haulmont/jmix-core#132]
**Environment**
Jmix version: 1.0.0-SNAPSHOT

**Precondition**
see https://github.com/Haulmont/jmix-core/issues/120 for more details

- Create an entity with embedded id
- Create screens, selecting all attributes in fetch plan
- Run the app

**TC 1**

1. Open browser
2. Create entity instance
3. Edit this instance - change id fields, save

**ER**
Instance is saved with new valued

**AR**
New instance created in addition to the old instance
![image](https://user-images.githubusercontent.com/73226373/113716863-100acb80-96fc-11eb-8430-be36d34d1751.png)

_____
**TC 2**

1. Open browser
2. Create several entity instances
3. Edit one instance - change id fields: set already existing values

**ER** 
Instance is not saved due to an error about unique constraint

**AR**
No errors, this instance is not changed, bit instance with the same id is edited with new values

**Comment by andreysubbotin** [comment]
It's not a bug. ID - uniquely identifies an entity, so it can't change after creation. 
A developer is able to disable ID fields in UI for the existing entity in a screen controller.
