### ISSUE TITLE
EntityNotEnhancedException after generating Data Model

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-core#134]
#### Enviroment:
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2735-202
IntelliJ version: IntelliJ IDEA 2021.1 (Community Edition)

#### TC:
1. Create new DB `u`  in DBeaver (for exaple Postgres) ->[run script.sql](https://app.zenhub.com/files/285281777/cf039aa1-a129-48ab-9c35-06b5caa580b7/download)
2. Open [attached](https://app.zenhub.com/files/285281777/3fbd9982-a226-4114-981f-5a50c2511c93/download) project
3. Run app
4. Open Sales Mapper browser or Sales Product browser

#### AR:
![image.png](https://images.zenhubusercontent.com/5ffd7dc3b256a97bde8addb9/d80df0d2-c90c-4c10-a9eb-66ee580f1972)
[Exception log](https://app.zenhub.com/files/285281777/cbc00749-f557-4163-9fdc-220c2d390e59/download)

**Comment by andreysubbotin** [comment]
Fixed in Haulmont/jmix-gradle-plugin#12
