### ISSUE TITLE
Enum properties with no JmixProperty annotation are not detected as entitiy property

### ISSUE THREAD

**Issue by KartonDCP** [Haulmont/jmix-core#150]
# Test case
* Create entity (dto NewEntity for example)
* Create enumeration
* Add this enum as property in your entitity(NewEntity)
* Go to the entity definition and check that enum prorety has no JmixProperty annotation
* Create screens for this entity
* Run application and go to the browser screen
* Try create new entity 
* Here `IllegalStateException`: Could not resolve property path 'newenum' in 'NewEntity' ![Снимок экрана (58)](https://user-images.githubusercontent.com/43281522/116533604-3e8a5980-a8ea-11eb-85cf-837083f7e08c.png)
* Stop application 
* Force add `@JmixProperty` to the enum property
* Studio will say Jmix: Field 'newenum' has redundant @JmixProperty annotation, ignore it ![Снимок экрана (60)](https://user-images.githubusercontent.com/43281522/116533603-3df1c300-a8ea-11eb-8207-38c9e0bb71cc.png)
* Run application and again try create NewEntity
* All fine

**Comment by bulgakovea** [comment]
can't reproduce
