### ISSUE TITLE
Application properties file uses ISO_8859_1 encoding by default

### ISSUE THREAD

**Issue by andreysubbotin** [Haulmont/jmix-core#154]
- Convert property values from UTF-8 to ISO_8859_1
- Use YAML for the properties file
- Other fixes.....

**Comment by andreysubbotin** [comment]
Jmix framework doesn't contain property files with UTF-8 encoding (all property files use ISO_8859_1). When the user sets the UTF property in the `application.property` file,  the Jmix Studio should convert the property value to ISO_8859_1.

**Comment by codingxu97** [comment]
> Jmix framework doesn't contain property files with UTF-8 encoding (all property files use ISO_8859_1). When the user sets the UTF property in the `application.properties` file, the Jmix Studio should convert the property value to ISO_8859_1.

Hi, @andreysubbotin !

Was there any way to make .properties file to keep UTF-8? Chinese in the ISO-8859-1 file couldn't be recognized in our code repository, so it troubled me a lot.
