### ISSUE TITLE
Port: Display of Kotlin enums messages

### ISSUE THREAD

**Issue by artemglinov** [Haulmont/jmix-core#204]
https://github.com/cuba-platform/cuba/issues/3156

**Comment by artemglinov** [comment]
### QA Notes

Test only correct display of Java enums messages after the fix port because Kotlin enums are not supported yet in Jmix.

**Comment by maistrenkoIulia** [comment]
kotlin is already supported by jmix
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3391-211
IntelliJ version: IntelliJ IDEA 2021.2 (Ultimate Edition)
[kotenum.zip](https://github.com/Haulmont/jmix-core/files/6960612/kotenum.zip)

![image](https://user-images.githubusercontent.com/66992566/128845174-e9936147-47ba-476a-b449-f823850ac1bf.png)

**Comment by artemglinov** [comment]
@maistrenkoIulia Set the messages for the enum entries (not only for the enum itself) in the attached project according to the Studio warnings. I've tried it, and it works.

**Comment by maistrenkoIulia** [comment]
verified
