### ISSUE TITLE
Http 404 error on logout

### ISSUE THREAD

**Issue by ange-diambote** [Haulmont/jmix-core#207]
I have set context prefix for my app, all work fine expect logout button.

**Comment by Flaurite** [comment]
Hello @ange-diambote,
Could you clarify what version of Jmix do you use? The problem was fixed in the 1.0.0 release version.

**Comment by ange-diambote** [comment]
0.9.0

**Comment by Flaurite** [comment]
Migrating to 1.0.0. release version should fix the problem

**Comment by ange-diambote** [comment]
Thanks, I do it now
