### ISSUE TITLE
Yaml file is not recognized by Configuration

### ISSUE THREAD

**Issue by Mr-CodingXu** [Haulmont/jmix-core#220]
My yaml file is not recognized by Configuration in jmix view.then I delete properties file,it does not help the matter.
![p1](https://user-images.githubusercontent.com/35094351/129833597-99d63704-c618-4f22-b3a5-c8e3fed2c38e.png)
![p2](https://user-images.githubusercontent.com/35094351/129833599-ba12e495-3184-4933-bc25-2579bb0d6e0e.png)

**Comment by knstvk** [comment]
Thanks for the report!
Created a Studio issue: https://youtrack.jmix.io/issue/JST-1996
