### ISSUE TITLE
Incorrect entity import for table with Identity column

### ISSUE THREAD

**Issue by zaharchenko-evgeny** [Haulmont/jmix-core#248]
Steps to reproduce issue:
1. Import the model from the table with an Identity column. Jmix Studio will create an entity with `@GeneratedValue(strategy = GenerationType.IDENTITY) ` annotated id column.
![image](https://user-images.githubusercontent.com/11453760/136791419-72491298-aabd-47cc-bc14-3ad118c3b8e5.png)

2. Create browser and editor screen
3. Create one object
4. Create another object

Expected result: will be created two objects
Actual result: the second object will rewrite the first object

Original issue: https://youtrack.haulmont.com/issue/SBER-1110

**Comment by gorbunkov** [comment]
I've created a postgres database with the following table:
```sql
CREATE TABLE color (
    color_id INT GENERATED ALWAYS AS IDENTITY,
    color_name VARCHAR NOT NULL
);
```
I created a new Jmix project (1.1.0-SNAPSHOT) and imported the model from the database. Studio generated the following entity:
```java
@DdlGeneration(value = DdlGeneration.DbScriptGenerationMode.DISABLED)
@JmixEntity
@Table(name = "color")
@Entity
public class Color {
    @Column(name = "color_id", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(name = "color_name", nullable = false)
    @Lob
    private String colorName;

    public String getColorName() {
        return colorName;
    }

    public void setColorName(String colorName) {
        this.colorName = colorName;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
}
```

I opened the color browser screen and created several colors there - everything works fine.

Here is my project: [jmix-identity-entity.zip](https://github.com/Haulmont/jmix-core/files/7353290/jmix-identity-entity.zip)

@zaharchenko-evgeny 
How can I reproduce your problem? It will be great if you provide a sample where the problem can be reproduced.
