### ISSUE TITLE
Menu items are lost after application restart

### ISSUE THREAD

**Issue by imorenov94** [Haulmont/jmix-core#252]
**Environment:**
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3602-212
IntelliJ version: IntelliJ IDEA 2021.2.2 (Ultimate Edition)
OS: Win10
JDK version: 11,17 
Gradle version: gradle-7.2
**Steps:**
1. Create a new project on any of JDK (17 or 11)
2. Run the app
3. Stop the app
4. Create a new entity with screens
5. Run the app
6. Cheсk that created screens are displayed in the app

**ER:** Created screen is displayed
**AR:** Screen isn't displayed in menu items
**P.S**  (In case if we use JDK 11) If to change the Gradle version from 7.2 to 7.0.2 it works correctly, and screens are displaying after restarting the app.
 The issue can be fixed if to use (.\gradlew clean assemble) command
 **Also should check** **[Test cases with hot deploy](https://youtrack.jmix.io/issue/JST-1934#focus=Comments-83-6125682.0-0)**  - the ticket in which the bug was found

**Comment by knstvk** [comment]
Update project templates with Gradle 7.3
