### ISSUE TITLE
 rtl interfaces is supported

### ISSUE THREAD

**Issue by AbdulRahmanOmarAlward** [Haulmont/jmix-core#298]
Do you support the orientation of the rtl interfaces?
And if not, where is the modification done so that rtl is supported?

**Comment by gorbunkov** [comment]
Jmix doesn't have automatic RTL support. You may try to define a style for particular UI components. This [post](https://forum.cuba-platform.com/t/right-to-left-support/885) gives an example how it might be done in CUBA. In Jmix it will probably be done in a similar way.
