### ISSUE TITLE
Refactor FetchPlan in core module

### ISSUE THREAD

**Issue by andreysubbotin** [Haulmont/jmix-core#3]
#Make FetchPlan immutable data class
#Move `copy, partialView, systemProperties` from FetchPlan to FetchPlanBuilder API. This will remove AppBeans from FetchPlan. 
#Remove FetchPlanParams
#The CUBA View should keep the old API

**Comment by dtaimanov** [comment]
To be discussed: 
 - Exclude `includeSystemProperties` parameter from `FetchPlan` and move to legacy `View`.  From now all audit and soft-delete attributes should be specified explicitly to appear in FetchPlan
