### ISSUE TITLE
Get rid of jmix.core.webContextName

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-core#36]
It duplicates `server.servlet.contextPath`

### QA
Steps to check the issue:
1. Download Sampler app: https://github.com/Haulmont/jmix-sampler
2. Launch the app. It should be available by the following URL: `http://localhost:8080/sampler`
3. Go to your browser settings, clear all cookies for `localhost`.
4. Go to page with Sampler, refresh the page.
5. Try to change application theme to some another (there is no exception should occur).
6. Check cookies for localhost. There should be cookie for last theme.

**Comment by maistrenkoIulia** [comment]
fixed
