### ISSUE TITLE
FileStorage should know about file name

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-core#39]
Currently io.jmix.core.FileStorage knows only some generic "file info" which can be anything:

>  @param `<I>` file info type

But reality is that UI library needs file name: 
- to download stored file with some name.
- to somehow display URI attributes in browser table or in editor form

Now there are only two implementations, and both of them use "I" = file name.

So UI code assumes that "I" is always file name:

```
// FileDownloadController
    protected FileStorage<URI, String> fileStorage;

        if (fileStorage == null) {
            fileStorage = fileStorageLocator.getDefault();
        }
...
String filename = fileStorage.getFileInfo(fileReference);
```

```
// FileStorageResourceImpl

String fullName = x
                ? y
                : getFileStorage().getFileInfo(fileReference).toString();
        String baseName = FilenameUtils.getBaseName(fullName);

...
        String extension = FilenameUtils.getExtension(fullName);
```

This is bad design.
FileStorage should somehow accept file name and return file name when necessary.

**Comment by knstvk** [comment]
What about adding `FileStorage.getFileInfoType()` method?
Then generic code working with file storage could check if it can actually work:
```
fileStorage = fileStorageLocator.getDefault();
if (fileStorage.getFileInfoType() != String.class) {
    log.warn("Cannot do this");
    return;
}
```

**Comment by alexbudarov** [comment]
I think it should be a dedicated `getFileName` method.
Every file storage should be able to store file name. If integrated service can't do it, an additional table a-la FileDescriptor can help.

**Comment by knstvk** [comment]
Let's also consider replacing generic FileInfo with string file name:
```
public interface FileStorage<R> {

    R createReference(String fileName);

    String getFileName(R reference);

    // ...
}
```

**Comment by glebshalyganov** [comment]
`<I>` file info type was removed from `FileStorage`.

Instead of it `FileStorage` now has the dedicated `getFileName` method.
> 
> ```
> public interface FileStorage<R> {
> 
>     R createReference(String fileName);
> 
>     String getFileName(R reference);
> 
>     // ...
> }
> ```
