### ISSUE TITLE
Application settings stored in database

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-core#56]
## Overview

A simple API and UI to work with mutable values of different types stored in database. These values are usually used as parameters of different functionality of the application.

## Proposed Solution

Store parameters in regular Jmix entities with some additional setup.

- Provide a superclass of entities used for settings, with `id` and `version` attributes
- Provide annotations for default values: @AppSettingsDefault, @AppSettingsDefaultBoolean, @AppSettingsDefaultInt, etc.
- Provide a service with load / save methods which accept settings entity class or instance.
- Provide a standard UI similar to EntityInspector

## Original description

https://doc.cuba-platform.com/manual-7.2/config_interface_usage.html

Storing configurable properties in Configuration interfaces with SourceType.DATABASE is one of the most benefitial, widely used CUBA features. It is so easy to use and the overhead is so little that it's almost recommended for developers to put all "potentially modifiable" business logic parameters to configuration interfaces.

https://www.baeldung.com/properties-with-spring
As I understand, Spring Boot doesn't provide storing properties in the database and immediate updating their values out of the box. Even spring-cloud config module uses the same paradigm - obtain values once when application starts and inject them to bean classes. No ability to change values in runtime.

You can't replace databased-stored properties with command-line parameters, environment variables or property files. Because database-stored properties can be editable by regular web UI user (non-sysadmin).

Database-stored config values look like one of important CUBA features bringing convenience for business apps, not having analogue in Boot ecosystem.

So we need to provide some replacement for the old functionality.
Requirements:
- values are stored in the persistent storage (not lost after full cluster restart)
- ability to change property value in the runtime and immediately apply this value to its users
- typed value conversion
- cluster support
- high performance: reading an already cached value shouldn't involve network or I/O access
- easy to deploy, easy to use in dev environment (no zookeeper, no mongo please. Yes, plain boring table in RDBMS)
- management UI would be nice (like Application Properties in CUBA)
- use Spring module or other library if any similar functionality is already provided by a popular module or library

Looks like it can be implemented in a Jmix add-on.

## Progress

Overall progress at 01.02.2022 ~90%
Progress
- [x] Implementation
    - [x] Create new add-on structure for requested functionality
        - [x] name of the add-on - "jmix-appsettings" - TBD
        - [x] short name - for beans and services - "apstng" - TBD  
    - [x] Support AppSettingsDefault* annotations for providing default vaues 
        - [x] AppSettingsDefaultBoolean
        - [x] AppSettingsDefaultDouble
        - [x] AppSettingsDefaultFloat
        - [x] AppSettingsDefaultInt
        - [x] AppSettingsDefaultLong
        - [x] AppSettngsDefault
    - [x] Implement logic for loading and saving settings entity consider default values
    - [x] Tests
    - [x] Java docs
    - [x] Provide admin screens for browse and edit settings entity (similar to Entity Inspector)

**Comment by andreysubbotin** [comment]
Spring cloud config properties refresh using `@RefreshScope` annotation and /actuator/refresh endpoint: https://soshace.com/spring-cloud-config-refresh-strategies/

**Comment by alexbudarov** [comment]
Part of spec.
