### ISSUE TITLE
Advanced support for Quartz scheduler

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-core#64]
- Configure job schedule
- Activate/deactivate a job
- Track and show execution history

Common progress for 17/01/2022 99%

## Progress

- [x] R&D - https://youtrack.haulmont.com/articles/PLAT-A-574/Scheduled-tasks-(Advanced-Quartz-support)
- [x] Specification 
- [x] Implementation
  - [x] UI screens implementation
  - [x] Integration with Quartz API
  - [x] Provide consistent work with different DBs (bring liquibase script for quartz tables into Jmix)
  - [x] Get rid of specifying driverDelegateClass 
  - [x] Add filter by Name/Group/Class/State for jobs browser
  - [x] Add description for job (browser and editor)
  - [x] Add more detailed examples for cron expressions with time
  - [x] Make name of trigger not required
  - [x] Add field 'Source' for job ['User defined' / 'Predefined']
  - [x] Add validation for unique job name
  - [x] Add validation for unique trigger name
  - [x] Make validation for job data parameters keys for uniqueness
  - [x] Move none-required field to bottom in trigger editor screen
  - [x] Support 'repeat forever' for trigger without repeatCount
- [x] Tests
- [x] Internal docs
  - [x] [RnD article](https://youtrack.haulmont.com/articles/PLAT-A-574/Scheduled-tasks-(Advanced-Quartz-support))
  - [x] [ADR article](https://youtrack.haulmont.com/articles/PLAT-A-588/ADR101-Advanced-support-for-Quartz-scheduler) 
  - [x] [Add-on Readme](https://youtrack.haulmont.com/articles/PLAT-A-595/Jmix-Quartz-add-on)
  - [x] Add description for usage of Job and Trigger listeners to keep execution history

**Comment by konyashkina** [comment]
Tested on: 

- [x] 1.2.0-SNAPSHOT
- [x] 1.2.0-RC1
