### ISSUE TITLE
Can not delete entity instance with one-to-many composition elements

### ISSUE THREAD

**Issue by lovtsovaik** [Haulmont/jmix-core#71]
Jmix platform version: 0.3.0-SNAPSHOT

1. Open the project [tomany.zip](https://github.com/Haulmont/jmix-core/files/5892979/tomany.zip)
2. Run the app
3. Open one of the screen in Application section: "WithCollComp browser", "WithCollComp m", "WithSetComp browser", "WithSetComp m" or "WithListComp browser"
4. Create new item with adding items in "comp" table or find such instance
5. Delete item

ER: the entity instance is deleted with its composition items
AR: errors (see [error log](https://github.com/Haulmont/jmix-core/files/5893038/error.txt) for more information):
![collection_composition](https://user-images.githubusercontent.com/73226373/106259991-5b56b880-6239-11eb-8973-0e7af41e489b.PNG)
![list_composition](https://user-images.githubusercontent.com/73226373/106259997-5d207c00-6239-11eb-82eb-d1da5f6ed6cb.PNG)
![set_composition](https://user-images.githubusercontent.com/73226373/106260002-5e51a900-6239-11eb-9e5f-c83c3497d067.PNG)

**Comment by andreysubbotin** [comment]
Entities without the soft-deletion trait and database FK constraints work when you delete objects. By default, FKs throws exceptions. 
Set  `FK constraint action` in Jmix Studio for the composition property. 
In that case, Jmix Studio should generate FK constraints with a specified deletion policy.

**Comment by DartVerder** [comment]
created ticket for Jmix Studio
https://youtrack.haulmont.com/issue/JST-1026
