### ISSUE TITLE
Refactor AttributeChanges and EntityAttributeChanges

### ISSUE THREAD

**Issue by dtaimanov** [Haulmont/jmix-core#72]
There are two similar classes in Jmix:
1. `io.jmix.core.event.AttributeChanges`
2. `io.jmix.data.impl.EntityAttributeChanges`

Second class does almost the same as first, but also provides extra functionality: e.g. get changes from  eclipselink's `AttributeChangeListener`, work with dynamic attributes [in progress]

#### Proposition

1. Make EntityAttributeChanges extend AttributeChanges to get rid of code duplication
2. Rename `EntityAttributeChanges` to something like `PersistentAttributeChanges` / `EclipselinkAttributeChanges`

**Comment by andreysubbotin** [comment]
Fixed in Haulmont/jmix-data#46
