### ISSUE TITLE
Can not edit entity from Oracle database

### ISSUE THREAD

**Issue by lovtsovaik** [Haulmont/jmix-core#85]
Jmix platform version: 0.3.0-SNAPSHOT

1. Open project [bdadd.zip](https://github.com/Haulmont/jmix-core/files/5965235/bdadd.zip)
2. Run application
3. Open "InOr browser"
4. Create an entity, save
5. Edit, save

AR: can not save because the app is trying to create instead of update
![image](https://user-images.githubusercontent.com/73226373/107638178-a84e7c00-6c88-11eb-901c-5835edd1049e.png)
[log_insert.txt](https://github.com/Haulmont/jmix-core/files/5965257/log_insert.txt)

There are no such errors for MS SQL and PostgreSQL.

ER: edited entity saved

**Comment by andreysubbotin** [comment]
Fixed in Haulmont/jmix-data#45
