### ISSUE TITLE
Unable to load entity from Oracle database

### ISSUE THREAD

**Issue by lovtsovaik** [Haulmont/jmix-core#86]
Jmix platform version: 0.3.0-SNAPSHOT

also see https://github.com/Haulmont/jmix-core/issues/85 bug with the same project
1. Open project [bdadd.zip](https://github.com/Haulmont/jmix-core/files/5965281/bdadd.zip)
2. Run application
3. Open "InOr browser"
4. Create an entity, save
5. Stop application
6. Run again
7. Open "InOr browser"
8. Edit existing entity

AR: Unable to load entity
![image](https://user-images.githubusercontent.com/73226373/107639097-e009f380-6c89-11eb-8a30-518cad31ac96.png)
[log_load.txt](https://github.com/Haulmont/jmix-core/files/5965293/log_load.txt)

There are no such errors for MS SQL and PostgreSQL.

ER: entity is enabled for editing

**Comment by andreysubbotin** [comment]
Fixed in Haulmont/jmix-data#45
Test with the latest Jmix Studio build.
