### ISSUE TITLE
ClassCastException when load file to URI filed

### ISSUE THREAD

**Issue by lovtsovaik** [Haulmont/jmix-core#91]
Jmix platform version: 0.3.0-SNAPSHOT

See https://github.com/Haulmont/jmix-core/issues/63

1. Open project [files.zip](https://github.com/Haulmont/jmix-core/files/5980664/files.zip)
2. Run app
3. Open WithFiles browser
4. Click Create button
5. Upload file to Urii field

AR: ClassCastException: io.jmix.core.FileRef cannot be cast to java.net.URI
![image](https://user-images.githubusercontent.com/73226373/107928170-6e83bb00-6f91-11eb-9d44-dbbc4d3a166c.png)
[ClassCastException_FileRef.txt](https://github.com/Haulmont/jmix-core/files/5980605/ClassCastException_FileRef.txt)

ER: load and save successful

**Comment by glebshalyganov** [comment]
File reference property should be of `FileRef` type, not `URI`.

**Comment by lovtsovaik** [comment]
Studio [ticket ](https://youtrack.haulmont.com/issue/JST-703) created for changing generated field for URI attribute
